name: Upload To Azure Blob Storage
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: /docs
          container_name: $web
          connection_string: ${{ secrets.Azure_blob }}
          extra_args: '--pattern *.tar.gz*'
