name: Upload To Azure
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: feeloor/azure-static-website-deploy@master
        env:
          SOURCE_DIR: "./"
          AZURE_CLIENT_ID: ${{ secret.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secret.AZURE_TENANT_ID }}
          AZURE_SECRET: ${{ secret.AZURE_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secret.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secret.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_INDEX_DOCUMENT_NAME: "index.html"
          AZURE_ERROR_DOCUMENT_NAME: "404.html"
